### ISSUE TITLE
empty norm.dat causing problems

### ISSUE THREAD

**Issue by cvanvelt** [AllenInstitute/scrattch.bigcat#2]
Following error when running iter_clust_big:

Error in rcpp_get_cl_means_transpose(mat, cl) : 
  Not compatible with STRSXP: [type=NULL].

 1: iter_clust_big(big.dat = big.dat, select.cells, de.param = de.param, rm.eigen = rm.eigen)
 2: cluster_big.R#255: onestep_clust_big(big.dat = big.dat, select.cells = select.cells, prefix = p
 3: cluster_big.R#193: merge_cl_big(big.dat, cl = cl, rd.dat = rd.dat, merge.type = merge.type, de.
 4: cluster_big.R#497: select_markers(norm.dat = NULL, cl, de.genes = de.genes, n.markers = 50, mc.
 5: de_all_pairs(norm.dat, cl, mc.cores = mc.cores, ...)
 6: de_selected_pairs(norm.dat, cl = cl, pairs = pairs, cl.bin = cl.bin, de.param = de.param, metho
 7: as.data.frame(get_cl_means(norm.dat, cl))
 8: get_cl_means(norm.dat, cl)
 9: get_cl_stats(mat, cl, stats = "means")
10: rcpp_get_cl_means_transpose(mat, cl)

norm.dat remains empty. Have not figured out cause or solution yet.

**Comment by yzizhen** [comment]
Have you checked if the names(cl) are included in colnames(norm.dat)?

**Comment by y-gao** [comment]
This might cause by parallel issues in R when creating big.dat file. You can regenerate the big.dat file without parallelization
