### ISSUE TITLE
Is that possible to provide the single-cell object file (R or anndata) for the Fig1 ?

### ISSUE THREAD

**Issue by ShaowenJ** [AllenInstitute/scrattch.bigcat#20]
Hi,
Thanks so much for the big project resource. We are very interested in the data set. 
As the title, 

Thanks!

**Comment by yzizhen** [comment]
You can find h5ad file here: 
https://github.com/AllenInstitute/abc_atlas_access/blob/main/descriptions/WMB-10X.md

**Comment by ShaowenJ** [comment]
Great, Thanks!
